namespace WindowsViewer
{
    public partial class Form1 : global::System.Windows.Forms.Form
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            try
            {
                base.Icon = global::System.Drawing.Icon.ExtractAssociatedIcon(global::System.Reflection.Assembly.GetExecutingAssembly().Location);
            }
            catch (global::System.ArgumentException)
            {
            }
            this.menuMain = new global::System.Windows.Forms.MenuStrip();
            this.aboutPhyziosStudioProToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.quitPhyziosStudioProToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.fileToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripMenuItem();
            this.newToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.openToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.saveToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.revertToSavedToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.editToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.undoToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.redoToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.cutToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.copyToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.pasteToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.deleteToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.deleteAllToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.selectAllToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.deselectAllToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.engineToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.pausedToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.movieCapturingToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.stToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.pointsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.crossesToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.circlesToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.bluredToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.contourToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.textureToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.boundsWallToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.gravityToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.playSoundToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.toolLimitToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.windowToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.toolboxToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.materialsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.colorToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.timeToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.propertiesToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.statusToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.browserToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.parametersToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.brigAllToFrontToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.hToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.pHYZIOSStudioProHelpToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.saveMovieFile = new global::System.Windows.Forms.SaveFileDialog();
            this.panel1 = new global::System.Windows.Forms.Panel();
            this.saveToLocalAndWebToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
            this.menuMain.SuspendLayout();
            base.SuspendLayout();
            this.menuMain.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.fileToolStripMenuItem1, this.editToolStripMenuItem, this.engineToolStripMenuItem, this.windowToolStripMenuItem, this.hToolStripMenuItem });
            this.menuMain.Location = new global::System.Drawing.Point(0, 0);
            this.menuMain.Name = "menuMain";
            this.menuMain.Padding = new global::System.Windows.Forms.Padding(0);
            this.menuMain.TabIndex = 0;
            this.menuMain.Text = "menuStrip1";
            this.aboutPhyziosStudioProToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.aboutPhyziosStudioProToolStripMenuItem.Name = "aboutPhyziosStudioProToolStripMenuItem";
            this.aboutPhyziosStudioProToolStripMenuItem.Text = "About PhyziosStudioPro";
            this.aboutPhyziosStudioProToolStripMenuItem.Click += new global::System.EventHandler(this.aboutPhyziosStudioProToolStripMenuItem_Click);
            this.quitPhyziosStudioProToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.quitPhyziosStudioProToolStripMenuItem.Name = "quitPhyziosStudioProToolStripMenuItem";
            this.quitPhyziosStudioProToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131153;
            this.quitPhyziosStudioProToolStripMenuItem.Text = "Quit";
            this.quitPhyziosStudioProToolStripMenuItem.Click += new global::System.EventHandler(this.quitPhyziosStudioProToolStripMenuItem_Click);
            this.fileToolStripMenuItem1.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.newToolStripMenuItem, this.openToolStripMenuItem, this.saveToolStripMenuItem, this.revertToSavedToolStripMenuItem, this.saveToLocalAndWebToolStripMenuItem });
            this.fileToolStripMenuItem1.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
            {
                new global::System.Windows.Forms.ToolStripSeparator(),
                this.quitPhyziosStudioProToolStripMenuItem
            });
            this.fileToolStripMenuItem1.Name = "fileToolStripMenuItem1";
            this.fileToolStripMenuItem1.Text = "File";
            this.fileToolStripMenuItem1.DropDownOpened += new global::System.EventHandler(this.fileToolStripMenuItem1_DropDownOpened);
            this.newToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.newToolStripMenuItem.Name = "newToolStripMenuItem";
            this.newToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131150;
            this.newToolStripMenuItem.Text = "New";
            this.newToolStripMenuItem.Click += new global::System.EventHandler(this.newToolStripMenuItem_Click);
            this.openToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.openToolStripMenuItem.Name = "openToolStripMenuItem";
            this.openToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131151;
            this.openToolStripMenuItem.Text = "Open";
            this.openToolStripMenuItem.Click += new global::System.EventHandler(this.openToolStripMenuItem_Click);
            this.saveToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            this.saveToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131155;
            this.saveToolStripMenuItem.Text = "Save";
            this.saveToolStripMenuItem.Click += new global::System.EventHandler(this.saveToolStripMenuItem_Click);
            this.revertToSavedToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.revertToSavedToolStripMenuItem.Name = "revertToSavedToolStripMenuItem";
            this.revertToSavedToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131154;
            this.revertToSavedToolStripMenuItem.Text = "Revert to Saved";
            this.revertToSavedToolStripMenuItem.Click += new global::System.EventHandler(this.revertToSavedToolStripMenuItem_Click);
            this.editToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.undoToolStripMenuItem, this.redoToolStripMenuItem, this.cutToolStripMenuItem, this.copyToolStripMenuItem, this.pasteToolStripMenuItem, this.deleteToolStripMenuItem, this.deleteAllToolStripMenuItem, this.selectAllToolStripMenuItem, this.deselectAllToolStripMenuItem });
            this.editToolStripMenuItem.Name = "editToolStripMenuItem";
            this.editToolStripMenuItem.Text = "Edit";
            this.editToolStripMenuItem.DropDownOpened += new global::System.EventHandler(this.editToolStripMenuItem_DropDownOpened);
            this.undoToolStripMenuItem.Name = "undoToolStripMenuItem";
            this.undoToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131162;
            this.undoToolStripMenuItem.Text = "Undo";
            this.undoToolStripMenuItem.Click += new global::System.EventHandler(this.undoToolStripMenuItem_Click);
            this.redoToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.redoToolStripMenuItem.Name = "redoToolStripMenuItem";
            this.redoToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)196698;
            this.redoToolStripMenuItem.Text = "Redo";
            this.redoToolStripMenuItem.Click += new global::System.EventHandler(this.redoToolStripMenuItem_Click);
            this.cutToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.cutToolStripMenuItem.Name = "cutToolStripMenuItem";
            this.cutToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131160;
            this.cutToolStripMenuItem.Text = "Cut";
            this.cutToolStripMenuItem.Click += new global::System.EventHandler(this.cutToolStripMenuItem_Click);
            this.copyToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
            this.copyToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131139;
            this.copyToolStripMenuItem.Text = "Copy";
            this.copyToolStripMenuItem.Click += new global::System.EventHandler(this.copyToolStripMenuItem_Click);
            this.pasteToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
            this.pasteToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131158;
            this.pasteToolStripMenuItem.Text = "Paste";
            this.pasteToolStripMenuItem.Click += new global::System.EventHandler(this.pasteToolStripMenuItem_Click);
            this.deleteToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
            this.deleteToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.Delete;
            this.deleteToolStripMenuItem.Text = "Delete";
            this.deleteToolStripMenuItem.Click += new global::System.EventHandler(this.deleteToolStripMenuItem_Click);
            this.deleteAllToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.deleteAllToolStripMenuItem.Name = "deleteAllToolStripMenuItem";
            this.deleteAllToolStripMenuItem.Text = "Delete All";
            this.deleteAllToolStripMenuItem.Click += new global::System.EventHandler(this.deleteAllToolStripMenuItem_Click);
            this.selectAllToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem";
            this.selectAllToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131137;
            this.selectAllToolStripMenuItem.Text = "Select All";
            this.selectAllToolStripMenuItem.Click += new global::System.EventHandler(this.selectAllToolStripMenuItem_Click);
            this.deselectAllToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.deselectAllToolStripMenuItem.Name = "deselectAllToolStripMenuItem";
            this.deselectAllToolStripMenuItem.Text = "Deselect All";
            this.deselectAllToolStripMenuItem.Click += new global::System.EventHandler(this.deselectAllToolStripMenuItem_Click);
            this.engineToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.pausedToolStripMenuItem, this.movieCapturingToolStripMenuItem, this.stToolStripMenuItem, this.boundsWallToolStripMenuItem, this.gravityToolStripMenuItem, this.playSoundToolStripMenuItem, this.toolLimitToolStripMenuItem });
            this.engineToolStripMenuItem.Name = "engineToolStripMenuItem";
            this.engineToolStripMenuItem.Text = "Engine";
            this.engineToolStripMenuItem.DropDownOpened += new global::System.EventHandler(this.engineToolStripMenuItem_DropDownOpened);
            this.pausedToolStripMenuItem.Checked = true;
            this.pausedToolStripMenuItem.CheckState = global::System.Windows.Forms.CheckState.Checked;
            this.pausedToolStripMenuItem.Name = "pausedToolStripMenuItem";
            this.pausedToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131152;
            this.pausedToolStripMenuItem.Text = "Paused";
            this.pausedToolStripMenuItem.Click += new global::System.EventHandler(this.pausedToolStripMenuItem_Click);
            this.movieCapturingToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.movieCapturingToolStripMenuItem.Name = "movieCapturingToolStripMenuItem";
            this.movieCapturingToolStripMenuItem.Text = "Movie Capturing";
            this.movieCapturingToolStripMenuItem.Click += new global::System.EventHandler(this.movieCapturingToolStripMenuItem_Click);
            this.stToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.pointsToolStripMenuItem, this.crossesToolStripMenuItem, this.circlesToolStripMenuItem, this.bluredToolStripMenuItem, this.contourToolStripMenuItem, this.textureToolStripMenuItem });
            this.stToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.stToolStripMenuItem.Name = "stToolStripMenuItem";
            this.stToolStripMenuItem.Text = "Style";
            this.stToolStripMenuItem.Click += new global::System.EventHandler(this.stToolStripMenuItem_Click);
            this.pointsToolStripMenuItem.Name = "pointsToolStripMenuItem";
            this.pointsToolStripMenuItem.Text = "Points";
            this.pointsToolStripMenuItem.Click += new global::System.EventHandler(this.pointsToolStripMenuItem_Click);
            this.crossesToolStripMenuItem.Name = "crossesToolStripMenuItem";
            this.crossesToolStripMenuItem.Text = "Crosses";
            this.crossesToolStripMenuItem.Click += new global::System.EventHandler(this.crossesToolStripMenuItem_Click);
            this.circlesToolStripMenuItem.Name = "circlesToolStripMenuItem";
            this.circlesToolStripMenuItem.Text = "Circles";
            this.circlesToolStripMenuItem.Click += new global::System.EventHandler(this.circlesToolStripMenuItem_Click);
            this.bluredToolStripMenuItem.Name = "bluredToolStripMenuItem";
            this.bluredToolStripMenuItem.Text = "Blurred";
            this.bluredToolStripMenuItem.Click += new global::System.EventHandler(this.bluredToolStripMenuItem_Click);
            this.contourToolStripMenuItem.Name = "contourToolStripMenuItem";
            this.contourToolStripMenuItem.Text = "Contour";
            this.contourToolStripMenuItem.Click += new global::System.EventHandler(this.contourToolStripMenuItem_Click);
            this.textureToolStripMenuItem.Name = "textureToolStripMenuItem";
            this.textureToolStripMenuItem.Text = "Texture";
            this.textureToolStripMenuItem.Click += new global::System.EventHandler(this.textureToolStripMenuItem_Click);
            this.boundsWallToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.boundsWallToolStripMenuItem.Name = "boundsWallToolStripMenuItem";
            this.boundsWallToolStripMenuItem.Text = "Bounds Wall";
            this.boundsWallToolStripMenuItem.Click += new global::System.EventHandler(this.boundsWallToolStripMenuItem_Click);
            this.gravityToolStripMenuItem.Name = "gravityToolStripMenuItem";
            this.gravityToolStripMenuItem.Text = "Gravity";
            this.gravityToolStripMenuItem.Click += new global::System.EventHandler(this.gravityToolStripMenuItem_Click);
            this.playSoundToolStripMenuItem.Name = "playSoundToolStripMenuItem";
            this.playSoundToolStripMenuItem.Text = "Play Sound";
            this.playSoundToolStripMenuItem.Click += new global::System.EventHandler(this.playSoundToolStripMenuItem_Click);
            this.toolLimitToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.toolLimitToolStripMenuItem.Name = "toolLimitToolStripMenuItem";
            this.toolLimitToolStripMenuItem.Text = "Tool Limit";
            this.toolLimitToolStripMenuItem.Click += new global::System.EventHandler(this.toolLimitToolStripMenuItem_Click);
            this.windowToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.toolboxToolStripMenuItem, this.materialsToolStripMenuItem, this.colorToolStripMenuItem, this.timeToolStripMenuItem, this.propertiesToolStripMenuItem, this.statusToolStripMenuItem, this.browserToolStripMenuItem, this.parametersToolStripMenuItem, this.brigAllToFrontToolStripMenuItem });
            this.windowToolStripMenuItem.Name = "windowToolStripMenuItem";
            this.windowToolStripMenuItem.Text = "Window";
            this.toolboxToolStripMenuItem.Name = "toolboxToolStripMenuItem";
            this.toolboxToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.LButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.toolboxToolStripMenuItem.Text = "Toolbox";
            this.toolboxToolStripMenuItem.Click += new global::System.EventHandler(this.toolboxToolStripMenuItem_Click);
            this.materialsToolStripMenuItem.Name = "materialsToolStripMenuItem";
            this.materialsToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.RButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.materialsToolStripMenuItem.Text = "Materials";
            this.materialsToolStripMenuItem.Click += new global::System.EventHandler(this.materialsToolStripMenuItem_Click);
            this.colorToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.colorToolStripMenuItem.Name = "colorToolStripMenuItem";
            this.colorToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.LButton | global::System.Windows.Forms.Keys.RButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.colorToolStripMenuItem.Text = "Color";
            this.colorToolStripMenuItem.Click += new global::System.EventHandler(this.colorToolStripMenuItem_Click);
            this.timeToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.timeToolStripMenuItem.Name = "timeToolStripMenuItem";
            this.timeToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.MButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.timeToolStripMenuItem.Text = "Time";
            this.timeToolStripMenuItem.Click += new global::System.EventHandler(this.timeToolStripMenuItem_Click);
            this.propertiesToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.propertiesToolStripMenuItem.Name = "propertiesToolStripMenuItem";
            this.propertiesToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.LButton | global::System.Windows.Forms.Keys.MButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.propertiesToolStripMenuItem.Text = "Properties";
            this.propertiesToolStripMenuItem.Click += new global::System.EventHandler(this.propertiesToolStripMenuItem_Click);
            this.statusToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.statusToolStripMenuItem.Name = "statusToolStripMenuItem";
            this.statusToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.RButton | global::System.Windows.Forms.Keys.MButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.statusToolStripMenuItem.Text = "Status";
            this.statusToolStripMenuItem.Click += new global::System.EventHandler(this.statusToolStripMenuItem_Click);
            this.browserToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.browserToolStripMenuItem.Name = "browserToolStripMenuItem";
            this.browserToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.LButton | global::System.Windows.Forms.Keys.RButton | global::System.Windows.Forms.Keys.MButton | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.browserToolStripMenuItem.Text = "Browser";
            this.browserToolStripMenuItem.Click += new global::System.EventHandler(this.browserToolStripMenuItem_Click);
            this.parametersToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.parametersToolStripMenuItem.Name = "parametersToolStripMenuItem";
            this.parametersToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.Back | global::System.Windows.Forms.Keys.ShiftKey | global::System.Windows.Forms.Keys.Space | global::System.Windows.Forms.Keys.Control;
            this.parametersToolStripMenuItem.Text = "Parameters";
            this.parametersToolStripMenuItem.Click += new global::System.EventHandler(this.parametersToolStripMenuItem_Click);
            this.brigAllToFrontToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.brigAllToFrontToolStripMenuItem.Name = "brigAllToFrontToolStripMenuItem";
            this.brigAllToFrontToolStripMenuItem.Text = "Bring All to Front";
            this.brigAllToFrontToolStripMenuItem.Click += new global::System.EventHandler(this.brigAllToFrontToolStripMenuItem_Click);
            this.hToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.pHYZIOSStudioProHelpToolStripMenuItem });
            this.hToolStripMenuItem.DropDownItems.Add(this.aboutPhyziosStudioProToolStripMenuItem);
            this.hToolStripMenuItem.Name = "hToolStripMenuItem";
            this.hToolStripMenuItem.Text = "Help";
            this.pHYZIOSStudioProHelpToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
            this.pHYZIOSStudioProHelpToolStripMenuItem.Name = "pHYZIOSStudioProHelpToolStripMenuItem";
            this.pHYZIOSStudioProHelpToolStripMenuItem.Text = "PHYZIOS Studio Pro Help";
            this.pHYZIOSStudioProHelpToolStripMenuItem.Click += new global::System.EventHandler(this.pHYZIOSStudioProHelpToolStripMenuItem_Click);
            this.saveMovieFile.DefaultExt = "avi";
            this.saveMovieFile.Filter = "AVI file|*.avi";
            this.panel1.AutoSize = true;
            this.panel1.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new global::System.Drawing.Point(0, 24);
            this.panel1.Margin = new global::System.Windows.Forms.Padding(0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new global::System.Drawing.Size(634, 456);
            this.panel1.TabIndex = 1;
            this.saveToLocalAndWebToolStripMenuItem.Name = "saveToLocalAndWebToolStripMenuItem";
            this.saveToLocalAndWebToolStripMenuItem.Text = "Save to Local and Web";
            this.saveToLocalAndWebToolStripMenuItem.Visible = false;
            this.saveToLocalAndWebToolStripMenuItem.Click += new global::System.EventHandler(this.saveToLocalAndWebToolStripMenuItem_Click);
            base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            base.ClientSize = new global::System.Drawing.Size(634, 480);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.menuMain);
            base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MainMenuStrip = this.menuMain;
            base.Name = "Form1";
            this.Text = "Form1";
            base.FormClosing += new global::System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            base.Load += new global::System.EventHandler(this.Form1_Load);
            base.KeyUp += new global::System.Windows.Forms.KeyEventHandler(this.Panel_KeyUp);
            base.PreviewKeyDown += new global::System.Windows.Forms.PreviewKeyDownEventHandler(this.Panel_PreviewKeyDown);
            base.Resize += new global::System.EventHandler(this.Form1_Resize);
            this.menuMain.ResumeLayout(false);
            this.menuMain.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        private global::System.ComponentModel.IContainer components;
        private global::System.Windows.Forms.MenuStrip menuMain;
        private global::System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem1;
        private global::System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem engineToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem windowToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem hToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem aboutPhyziosStudioProToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem quitPhyziosStudioProToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem revertToSavedToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem undoToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem redoToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem cutToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem copyToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem pasteToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem deleteAllToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem selectAllToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem deselectAllToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem pausedToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem movieCapturingToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem stToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem boundsWallToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem gravityToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem playSoundToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem toolLimitToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem toolboxToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem materialsToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem colorToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem timeToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem propertiesToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem statusToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem browserToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem parametersToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem brigAllToFrontToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem pHYZIOSStudioProHelpToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem pointsToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem crossesToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem circlesToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem bluredToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem contourToolStripMenuItem;
        private global::System.Windows.Forms.ToolStripMenuItem textureToolStripMenuItem;
        private global::System.Windows.Forms.SaveFileDialog saveMovieFile;
        private global::System.Windows.Forms.Panel panel1;
        private global::System.Windows.Forms.ToolStripMenuItem saveToLocalAndWebToolStripMenuItem;
    }
}
