namespace WindowsViewer
{
    public partial class PropertyForm : global::System.Windows.Forms.Form
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.groupScene = new global::System.Windows.Forms.GroupBox();
            this.textBoxTags = new global::System.Windows.Forms.TextBox();
            this.label22 = new global::System.Windows.Forms.Label();
            this.textBoxSceneDescription = new global::System.Windows.Forms.TextBox();
            this.textBoxSceneTitle = new global::System.Windows.Forms.TextBox();
            this.checkBoxPublish = new global::System.Windows.Forms.CheckBox();
            this.label2 = new global::System.Windows.Forms.Label();
            this.label1 = new global::System.Windows.Forms.Label();
            this.groupSize = new global::System.Windows.Forms.GroupBox();
            this.textBoxParticleSize = new global::System.Windows.Forms.TextBox();
            this.textBoxSceneHeight = new global::System.Windows.Forms.TextBox();
            this.textBoxSceneWidth = new global::System.Windows.Forms.TextBox();
            this.btnSizeDefault = new global::System.Windows.Forms.Button();
            this.label6 = new global::System.Windows.Forms.Label();
            this.comboBoxPixelsH = new global::System.Windows.Forms.ComboBox();
            this.comboBoxPixelsW = new global::System.Windows.Forms.ComboBox();
            this.label5 = new global::System.Windows.Forms.Label();
            this.label4 = new global::System.Windows.Forms.Label();
            this.label3 = new global::System.Windows.Forms.Label();
            this.groupBox1 = new global::System.Windows.Forms.GroupBox();
            this.checkBubbleEffect = new global::System.Windows.Forms.CheckBox();
            this.checkSplashEffect = new global::System.Windows.Forms.CheckBox();
            this.checkFireEffect = new global::System.Windows.Forms.CheckBox();
            this.checkToolLimit = new global::System.Windows.Forms.CheckBox();
            this.checkSound = new global::System.Windows.Forms.CheckBox();
            this.checkBoundsWall = new global::System.Windows.Forms.CheckBox();
            this.groupBox2 = new global::System.Windows.Forms.GroupBox();
            this.label8 = new global::System.Windows.Forms.Label();
            this.textBoxGravityAngle = new global::System.Windows.Forms.TextBox();
            this.trackBarGravityAngle = new global::System.Windows.Forms.TrackBar();
            this.textBoxGravityAcc = new global::System.Windows.Forms.TextBox();
            this.label7 = new global::System.Windows.Forms.Label();
            this.trackGravityAcc = new global::System.Windows.Forms.TrackBar();
            this.checkGravity = new global::System.Windows.Forms.CheckBox();
            this.groupBox3 = new global::System.Windows.Forms.GroupBox();
            this.textBoxBScrollY = new global::System.Windows.Forms.TextBox();
            this.textBoxBScrollX = new global::System.Windows.Forms.TextBox();
            this.label13 = new global::System.Windows.Forms.Label();
            this.textBoxFScrollY = new global::System.Windows.Forms.TextBox();
            this.textBoxFScrollX = new global::System.Windows.Forms.TextBox();
            this.label12 = new global::System.Windows.Forms.Label();
            this.textBoxAScrollY = new global::System.Windows.Forms.TextBox();
            this.textBoxAScrollX = new global::System.Windows.Forms.TextBox();
            this.label11 = new global::System.Windows.Forms.Label();
            this.checkSleepOOV = new global::System.Windows.Forms.CheckBox();
            this.checkWorldBounds = new global::System.Windows.Forms.CheckBox();
            this.label10 = new global::System.Windows.Forms.Label();
            this.label9 = new global::System.Windows.Forms.Label();
            this.textBoxWorldY1 = new global::System.Windows.Forms.TextBox();
            this.textBoxWorldX1 = new global::System.Windows.Forms.TextBox();
            this.textBoxWorldY0 = new global::System.Windows.Forms.TextBox();
            this.textBoxWorldX0 = new global::System.Windows.Forms.TextBox();
            this.textBoxViewY1 = new global::System.Windows.Forms.TextBox();
            this.textBoxViewX1 = new global::System.Windows.Forms.TextBox();
            this.textBoxViewY0 = new global::System.Windows.Forms.TextBox();
            this.textBoxViewX0 = new global::System.Windows.Forms.TextBox();
            this.groupBox4 = new global::System.Windows.Forms.GroupBox();
            this.label15 = new global::System.Windows.Forms.Label();
            this.label14 = new global::System.Windows.Forms.Label();
            this.btnBGColor = new global::System.Windows.Forms.Button();
            this.comboBoxStyle = new global::System.Windows.Forms.ComboBox();
            this.groupBox5 = new global::System.Windows.Forms.GroupBox();
            this.comboBoxBubbleTexture = new global::System.Windows.Forms.ComboBox();
            this.label21 = new global::System.Windows.Forms.Label();
            this.comboBoxSplashTexture = new global::System.Windows.Forms.ComboBox();
            this.label20 = new global::System.Windows.Forms.Label();
            this.comboBoxFireTexture = new global::System.Windows.Forms.ComboBox();
            this.label19 = new global::System.Windows.Forms.Label();
            this.comboBoxWaterTexture = new global::System.Windows.Forms.ComboBox();
            this.label18 = new global::System.Windows.Forms.Label();
            this.comboBoxBackTexture = new global::System.Windows.Forms.ComboBox();
            this.label17 = new global::System.Windows.Forms.Label();
            this.comboBoxForeTexture = new global::System.Windows.Forms.ComboBox();
            this.label16 = new global::System.Windows.Forms.Label();
            this.colorDialogBGColor = new global::System.Windows.Forms.ColorDialog();
            this.openFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
            this.btnSizeApply = new global::System.Windows.Forms.Button();
            this.groupScene.SuspendLayout();
            this.groupSize.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((global::System.ComponentModel.ISupportInitialize)this.trackBarGravityAngle).BeginInit();
            ((global::System.ComponentModel.ISupportInitialize)this.trackGravityAcc).BeginInit();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            base.SuspendLayout();
            this.groupScene.Controls.Add(this.textBoxTags);
            this.groupScene.Controls.Add(this.label22);
            this.groupScene.Controls.Add(this.textBoxSceneDescription);
            this.groupScene.Controls.Add(this.textBoxSceneTitle);
            this.groupScene.Controls.Add(this.checkBoxPublish);
            this.groupScene.Controls.Add(this.label2);
            this.groupScene.Controls.Add(this.label1);
            this.groupScene.Location = new global::System.Drawing.Point(12, 12);
            this.groupScene.Name = "groupScene";
            this.groupScene.Size = new global::System.Drawing.Size(352, 201);
            this.groupScene.TabIndex = 0;
            this.groupScene.TabStop = false;
            this.groupScene.Text = "Scene";
            this.textBoxTags.Location = new global::System.Drawing.Point(92, 66);
            this.textBoxTags.MaxLength = 310;
            this.textBoxTags.Name = "textBoxTags";
            this.textBoxTags.Size = new global::System.Drawing.Size(245, 19);
            this.textBoxTags.TabIndex = 6;
            this.textBoxTags.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxTags.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.label22.AutoSize = true;
            this.label22.Location = new global::System.Drawing.Point(23, 69);
            this.label22.Name = "label22";
            this.label22.Size = new global::System.Drawing.Size(32, 12);
            this.label22.TabIndex = 5;
            this.label22.Text = "Tags:";
            this.textBoxSceneDescription.Location = new global::System.Drawing.Point(91, 101);
            this.textBoxSceneDescription.MaxLength = 500;
            this.textBoxSceneDescription.Multiline = true;
            this.textBoxSceneDescription.Name = "textBoxSceneDescription";
            this.textBoxSceneDescription.Size = new global::System.Drawing.Size(245, 50);
            this.textBoxSceneDescription.TabIndex = 4;
            this.textBoxSceneDescription.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxSceneDescription.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxSceneTitle.Location = new global::System.Drawing.Point(91, 32);
            this.textBoxSceneTitle.MaxLength = 24;
            this.textBoxSceneTitle.Name = "textBoxSceneTitle";
            this.textBoxSceneTitle.Size = new global::System.Drawing.Size(245, 19);
            this.textBoxSceneTitle.TabIndex = 3;
            this.textBoxSceneTitle.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxSceneTitle.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.checkBoxPublish.AutoSize = true;
            this.checkBoxPublish.Location = new global::System.Drawing.Point(25, 169);
            this.checkBoxPublish.Name = "checkBoxPublish";
            this.checkBoxPublish.Size = new global::System.Drawing.Size(61, 16);
            this.checkBoxPublish.TabIndex = 2;
            this.checkBoxPublish.Text = "Publish";
            this.checkBoxPublish.UseVisualStyleBackColor = true;
            this.checkBoxPublish.CheckedChanged += new global::System.EventHandler(this.checkBoxPublish_CheckedChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new global::System.Drawing.Point(23, 104);
            this.label2.Name = "label2";
            this.label2.Size = new global::System.Drawing.Size(65, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "Description:";
            this.label1.AutoSize = true;
            this.label1.Location = new global::System.Drawing.Point(23, 35);
            this.label1.Name = "label1";
            this.label1.Size = new global::System.Drawing.Size(30, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "Title:";
            this.groupSize.Controls.Add(this.btnSizeApply);
            this.groupSize.Controls.Add(this.textBoxParticleSize);
            this.groupSize.Controls.Add(this.textBoxSceneHeight);
            this.groupSize.Controls.Add(this.textBoxSceneWidth);
            this.groupSize.Controls.Add(this.btnSizeDefault);
            this.groupSize.Controls.Add(this.label6);
            this.groupSize.Controls.Add(this.comboBoxPixelsH);
            this.groupSize.Controls.Add(this.comboBoxPixelsW);
            this.groupSize.Controls.Add(this.label5);
            this.groupSize.Controls.Add(this.label4);
            this.groupSize.Controls.Add(this.label3);
            this.groupSize.Location = new global::System.Drawing.Point(12, 219);
            this.groupSize.Name = "groupSize";
            this.groupSize.Size = new global::System.Drawing.Size(352, 166);
            this.groupSize.TabIndex = 1;
            this.groupSize.TabStop = false;
            this.groupSize.Text = "Size";
            this.textBoxParticleSize.Location = new global::System.Drawing.Point(144, 95);
            this.textBoxParticleSize.Name = "textBoxParticleSize";
            this.textBoxParticleSize.Size = new global::System.Drawing.Size(107, 19);
            this.textBoxParticleSize.TabIndex = 12;
            this.textBoxParticleSize.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
            this.textBoxParticleSize.DragLeave += new global::System.EventHandler(this.textBoxSceneWidth_DragLeave);
            this.textBoxParticleSize.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneWidth_KeyDown);
            this.textBoxSceneHeight.Location = new global::System.Drawing.Point(144, 61);
            this.textBoxSceneHeight.Name = "textBoxSceneHeight";
            this.textBoxSceneHeight.Size = new global::System.Drawing.Size(107, 19);
            this.textBoxSceneHeight.TabIndex = 11;
            this.textBoxSceneHeight.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
            this.textBoxSceneHeight.DragLeave += new global::System.EventHandler(this.textBoxSceneWidth_DragLeave);
            this.textBoxSceneHeight.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneWidth_KeyDown);
            this.textBoxSceneWidth.Location = new global::System.Drawing.Point(144, 27);
            this.textBoxSceneWidth.Name = "textBoxSceneWidth";
            this.textBoxSceneWidth.Size = new global::System.Drawing.Size(107, 19);
            this.textBoxSceneWidth.TabIndex = 10;
            this.textBoxSceneWidth.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
            this.textBoxSceneWidth.DragLeave += new global::System.EventHandler(this.textBoxSceneWidth_DragLeave);
            this.textBoxSceneWidth.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneWidth_KeyDown);
            this.btnSizeDefault.Location = new global::System.Drawing.Point(261, 137);
            this.btnSizeDefault.Name = "btnSizeDefault";
            this.btnSizeDefault.Size = new global::System.Drawing.Size(75, 23);
            this.btnSizeDefault.TabIndex = 9;
            this.btnSizeDefault.Text = "Default";
            this.btnSizeDefault.UseVisualStyleBackColor = true;
            this.btnSizeDefault.Click += new global::System.EventHandler(this.btnSizeDefault_Click);
            this.label6.AutoSize = true;
            this.label6.Location = new global::System.Drawing.Point(261, 98);
            this.label6.Name = "label6";
            this.label6.Size = new global::System.Drawing.Size(36, 12);
            this.label6.TabIndex = 8;
            this.label6.Text = "Pixels";
            this.comboBoxPixelsH.FormattingEnabled = true;
            this.comboBoxPixelsH.Items.AddRange(new object[] { "Pixels", "Particles" });
            this.comboBoxPixelsH.Location = new global::System.Drawing.Point(263, 61);
            this.comboBoxPixelsH.Name = "comboBoxPixelsH";
            this.comboBoxPixelsH.Size = new global::System.Drawing.Size(73, 20);
            this.comboBoxPixelsH.TabIndex = 7;
            this.comboBoxPixelsH.Text = "Pixels";
            this.comboBoxPixelsH.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxPixelsW_SelectedIndexChanged);
            this.comboBoxPixelsW.FormattingEnabled = true;
            this.comboBoxPixelsW.Items.AddRange(new object[] { "Pixels", "Particles" });
            this.comboBoxPixelsW.Location = new global::System.Drawing.Point(263, 27);
            this.comboBoxPixelsW.Name = "comboBoxPixelsW";
            this.comboBoxPixelsW.Size = new global::System.Drawing.Size(73, 20);
            this.comboBoxPixelsW.TabIndex = 6;
            this.comboBoxPixelsW.Text = "Pixels";
            this.comboBoxPixelsW.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxPixelsW_SelectedIndexChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new global::System.Drawing.Point(23, 98);
            this.label5.Name = "label5";
            this.label5.Size = new global::System.Drawing.Size(71, 12);
            this.label5.TabIndex = 2;
            this.label5.Text = "Particle Size:";
            this.label4.AutoSize = true;
            this.label4.Location = new global::System.Drawing.Point(23, 64);
            this.label4.Name = "label4";
            this.label4.Size = new global::System.Drawing.Size(40, 12);
            this.label4.TabIndex = 1;
            this.label4.Text = "Height:";
            this.label3.AutoSize = true;
            this.label3.Location = new global::System.Drawing.Point(23, 30);
            this.label3.Name = "label3";
            this.label3.Size = new global::System.Drawing.Size(35, 12);
            this.label3.TabIndex = 0;
            this.label3.Text = "Width:";
            this.groupBox1.Controls.Add(this.checkBubbleEffect);
            this.groupBox1.Controls.Add(this.checkSplashEffect);
            this.groupBox1.Controls.Add(this.checkFireEffect);
            this.groupBox1.Controls.Add(this.checkToolLimit);
            this.groupBox1.Controls.Add(this.checkSound);
            this.groupBox1.Controls.Add(this.checkBoundsWall);
            this.groupBox1.Location = new global::System.Drawing.Point(12, 391);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new global::System.Drawing.Size(352, 132);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Models";
            this.checkBubbleEffect.AutoSize = true;
            this.checkBubbleEffect.Location = new global::System.Drawing.Point(197, 97);
            this.checkBubbleEffect.Name = "checkBubbleEffect";
            this.checkBubbleEffect.Size = new global::System.Drawing.Size(94, 16);
            this.checkBubbleEffect.TabIndex = 5;
            this.checkBubbleEffect.Text = "Bubble Effect";
            this.checkBubbleEffect.UseVisualStyleBackColor = true;
            this.checkBubbleEffect.CheckedChanged += new global::System.EventHandler(this.checkBubbleEffect_CheckedChanged);
            this.checkSplashEffect.AutoSize = true;
            this.checkSplashEffect.Location = new global::System.Drawing.Point(197, 64);
            this.checkSplashEffect.Name = "checkSplashEffect";
            this.checkSplashEffect.Size = new global::System.Drawing.Size(93, 16);
            this.checkSplashEffect.TabIndex = 4;
            this.checkSplashEffect.Text = "Splash Effect";
            this.checkSplashEffect.UseVisualStyleBackColor = true;
            this.checkSplashEffect.CheckedChanged += new global::System.EventHandler(this.checkSplashEffect_CheckedChanged);
            this.checkFireEffect.AutoSize = true;
            this.checkFireEffect.Location = new global::System.Drawing.Point(197, 30);
            this.checkFireEffect.Name = "checkFireEffect";
            this.checkFireEffect.Size = new global::System.Drawing.Size(79, 16);
            this.checkFireEffect.TabIndex = 3;
            this.checkFireEffect.Text = "Fire Effect";
            this.checkFireEffect.UseVisualStyleBackColor = true;
            this.checkFireEffect.CheckedChanged += new global::System.EventHandler(this.checkFireEffect_CheckedChanged);
            this.checkToolLimit.AutoSize = true;
            this.checkToolLimit.Location = new global::System.Drawing.Point(25, 97);
            this.checkToolLimit.Name = "checkToolLimit";
            this.checkToolLimit.Size = new global::System.Drawing.Size(75, 16);
            this.checkToolLimit.TabIndex = 2;
            this.checkToolLimit.Text = "Tool Limit";
            this.checkToolLimit.UseVisualStyleBackColor = true;
            this.checkToolLimit.CheckedChanged += new global::System.EventHandler(this.checkToolLimit_CheckedChanged);
            this.checkSound.AutoSize = true;
            this.checkSound.Location = new global::System.Drawing.Point(25, 64);
            this.checkSound.Name = "checkSound";
            this.checkSound.Size = new global::System.Drawing.Size(55, 16);
            this.checkSound.TabIndex = 1;
            this.checkSound.Text = "Sound";
            this.checkSound.UseVisualStyleBackColor = true;
            this.checkSound.CheckedChanged += new global::System.EventHandler(this.checkSound_CheckedChanged);
            this.checkBoundsWall.AutoSize = true;
            this.checkBoundsWall.Location = new global::System.Drawing.Point(25, 30);
            this.checkBoundsWall.Name = "checkBoundsWall";
            this.checkBoundsWall.Size = new global::System.Drawing.Size(83, 16);
            this.checkBoundsWall.TabIndex = 0;
            this.checkBoundsWall.Text = "BoundsWall";
            this.checkBoundsWall.UseVisualStyleBackColor = true;
            this.checkBoundsWall.CheckedChanged += new global::System.EventHandler(this.checkBoundsWall_CheckedChanged);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.textBoxGravityAngle);
            this.groupBox2.Controls.Add(this.trackBarGravityAngle);
            this.groupBox2.Controls.Add(this.textBoxGravityAcc);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.trackGravityAcc);
            this.groupBox2.Controls.Add(this.checkGravity);
            this.groupBox2.Location = new global::System.Drawing.Point(12, 529);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new global::System.Drawing.Size(352, 152);
            this.groupBox2.TabIndex = 3;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Gravity";
            this.label8.AutoSize = true;
            this.label8.Location = new global::System.Drawing.Point(23, 96);
            this.label8.Name = "label8";
            this.label8.Size = new global::System.Drawing.Size(36, 12);
            this.label8.TabIndex = 6;
            this.label8.Text = "Angle:";
            this.textBoxGravityAngle.Location = new global::System.Drawing.Point(280, 93);
            this.textBoxGravityAngle.Name = "textBoxGravityAngle";
            this.textBoxGravityAngle.Size = new global::System.Drawing.Size(56, 19);
            this.textBoxGravityAngle.TabIndex = 5;
            this.textBoxGravityAngle.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxGravityAngle_KeyDown);
            this.textBoxGravityAngle.Leave += new global::System.EventHandler(this.textBoxGravityAngle_Leave);
            this.trackBarGravityAngle.Location = new global::System.Drawing.Point(114, 84);
            this.trackBarGravityAngle.Maximum = 180;
            this.trackBarGravityAngle.Minimum = -180;
            this.trackBarGravityAngle.Name = "trackBarGravityAngle";
            this.trackBarGravityAngle.Size = new global::System.Drawing.Size(160, 45);
            this.trackBarGravityAngle.TabIndex = 4;
            this.trackBarGravityAngle.TickFrequency = 10;
            this.trackBarGravityAngle.TickStyle = global::System.Windows.Forms.TickStyle.Both;
            this.trackBarGravityAngle.Scroll += new global::System.EventHandler(this.trackBarGravityAngle_Scroll);
            this.textBoxGravityAcc.Location = new global::System.Drawing.Point(280, 48);
            this.textBoxGravityAcc.Name = "textBoxGravityAcc";
            this.textBoxGravityAcc.Size = new global::System.Drawing.Size(56, 19);
            this.textBoxGravityAcc.TabIndex = 3;
            this.textBoxGravityAcc.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxGravityAcc_KeyDown);
            this.textBoxGravityAcc.Leave += new global::System.EventHandler(this.textBoxGravityAcc_Leave);
            this.label7.AutoSize = true;
            this.label7.Location = new global::System.Drawing.Point(23, 51);
            this.label7.Name = "label7";
            this.label7.Size = new global::System.Drawing.Size(71, 12);
            this.label7.TabIndex = 2;
            this.label7.Text = "Acceleration:";
            this.trackGravityAcc.Location = new global::System.Drawing.Point(114, 36);
            this.trackGravityAcc.Maximum = 100;
            this.trackGravityAcc.Name = "trackGravityAcc";
            this.trackGravityAcc.Size = new global::System.Drawing.Size(160, 45);
            this.trackGravityAcc.TabIndex = 1;
            this.trackGravityAcc.TickFrequency = 10;
            this.trackGravityAcc.TickStyle = global::System.Windows.Forms.TickStyle.Both;
            this.trackGravityAcc.Scroll += new global::System.EventHandler(this.trackGravityAcc_Scroll);
            this.checkGravity.AutoSize = true;
            this.checkGravity.Location = new global::System.Drawing.Point(25, 18);
            this.checkGravity.Name = "checkGravity";
            this.checkGravity.Size = new global::System.Drawing.Size(61, 16);
            this.checkGravity.TabIndex = 0;
            this.checkGravity.Text = "Gravity";
            this.checkGravity.UseVisualStyleBackColor = true;
            this.checkGravity.CheckedChanged += new global::System.EventHandler(this.checkGravity_CheckedChanged);
            this.groupBox3.Controls.Add(this.textBoxBScrollY);
            this.groupBox3.Controls.Add(this.textBoxBScrollX);
            this.groupBox3.Controls.Add(this.label13);
            this.groupBox3.Controls.Add(this.textBoxFScrollY);
            this.groupBox3.Controls.Add(this.textBoxFScrollX);
            this.groupBox3.Controls.Add(this.label12);
            this.groupBox3.Controls.Add(this.textBoxAScrollY);
            this.groupBox3.Controls.Add(this.textBoxAScrollX);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.checkSleepOOV);
            this.groupBox3.Controls.Add(this.checkWorldBounds);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.textBoxWorldY1);
            this.groupBox3.Controls.Add(this.textBoxWorldX1);
            this.groupBox3.Controls.Add(this.textBoxWorldY0);
            this.groupBox3.Controls.Add(this.textBoxWorldX0);
            this.groupBox3.Controls.Add(this.textBoxViewY1);
            this.groupBox3.Controls.Add(this.textBoxViewX1);
            this.groupBox3.Controls.Add(this.textBoxViewY0);
            this.groupBox3.Controls.Add(this.textBoxViewX0);
            this.groupBox3.Location = new global::System.Drawing.Point(13, 687);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new global::System.Drawing.Size(351, 215);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Scroll";
            this.textBoxBScrollY.Location = new global::System.Drawing.Point(244, 178);
            this.textBoxBScrollY.Name = "textBoxBScrollY";
            this.textBoxBScrollY.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxBScrollY.TabIndex = 20;
            this.textBoxBScrollY.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxBScrollY.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxBScrollX.Location = new global::System.Drawing.Point(144, 178);
            this.textBoxBScrollX.Name = "textBoxBScrollX";
            this.textBoxBScrollX.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxBScrollX.TabIndex = 19;
            this.textBoxBScrollX.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxBScrollX.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.label13.AutoSize = true;
            this.label13.Location = new global::System.Drawing.Point(23, 181);
            this.label13.Name = "label13";
            this.label13.Size = new global::System.Drawing.Size(67, 12);
            this.label13.TabIndex = 18;
            this.label13.Text = "Background:";
            this.textBoxFScrollY.Location = new global::System.Drawing.Point(244, 153);
            this.textBoxFScrollY.Name = "textBoxFScrollY";
            this.textBoxFScrollY.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxFScrollY.TabIndex = 17;
            this.textBoxFScrollY.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxFScrollY.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxFScrollX.Location = new global::System.Drawing.Point(144, 153);
            this.textBoxFScrollX.Name = "textBoxFScrollX";
            this.textBoxFScrollX.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxFScrollX.TabIndex = 16;
            this.textBoxFScrollX.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxFScrollX.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.label12.AutoSize = true;
            this.label12.Location = new global::System.Drawing.Point(23, 156);
            this.label12.Name = "label12";
            this.label12.Size = new global::System.Drawing.Size(64, 12);
            this.label12.TabIndex = 15;
            this.label12.Text = "Foreground:";
            this.textBoxAScrollY.Location = new global::System.Drawing.Point(244, 128);
            this.textBoxAScrollY.Name = "textBoxAScrollY";
            this.textBoxAScrollY.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxAScrollY.TabIndex = 14;
            this.textBoxAScrollY.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxAScrollY.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxAScrollX.Location = new global::System.Drawing.Point(144, 128);
            this.textBoxAScrollX.Name = "textBoxAScrollX";
            this.textBoxAScrollX.Size = new global::System.Drawing.Size(92, 19);
            this.textBoxAScrollX.TabIndex = 13;
            this.textBoxAScrollX.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxAScrollX.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.label11.AutoSize = true;
            this.label11.Location = new global::System.Drawing.Point(23, 131);
            this.label11.Name = "label11";
            this.label11.Size = new global::System.Drawing.Size(59, 12);
            this.label11.TabIndex = 12;
            this.label11.Text = "Autoscroll:";
            this.checkSleepOOV.AutoSize = true;
            this.checkSleepOOV.Location = new global::System.Drawing.Point(150, 57);
            this.checkSleepOOV.Name = "checkSleepOOV";
            this.checkSleepOOV.Size = new global::System.Drawing.Size(138, 16);
            this.checkSleepOOV.TabIndex = 11;
            this.checkSleepOOV.Text = "Sleep Outside of View";
            this.checkSleepOOV.UseVisualStyleBackColor = true;
            this.checkSleepOOV.CheckedChanged += new global::System.EventHandler(this.checkSleepOOV_CheckedChanged);
            this.checkWorldBounds.AutoSize = true;
            this.checkWorldBounds.Location = new global::System.Drawing.Point(25, 57);
            this.checkWorldBounds.Name = "checkWorldBounds";
            this.checkWorldBounds.Size = new global::System.Drawing.Size(94, 16);
            this.checkWorldBounds.TabIndex = 10;
            this.checkWorldBounds.Text = "World Bounds";
            this.checkWorldBounds.UseVisualStyleBackColor = true;
            this.checkWorldBounds.CheckedChanged += new global::System.EventHandler(this.checkWorldBounds_CheckedChanged);
            this.label10.AutoSize = true;
            this.label10.Location = new global::System.Drawing.Point(23, 82);
            this.label10.Name = "label10";
            this.label10.Size = new global::System.Drawing.Size(35, 12);
            this.label10.TabIndex = 9;
            this.label10.Text = "World:";
            this.label9.AutoSize = true;
            this.label9.Location = new global::System.Drawing.Point(23, 21);
            this.label9.Name = "label9";
            this.label9.Size = new global::System.Drawing.Size(32, 12);
            this.label9.TabIndex = 8;
            this.label9.Text = "View:";
            this.textBoxWorldY1.Location = new global::System.Drawing.Point(278, 79);
            this.textBoxWorldY1.Name = "textBoxWorldY1";
            this.textBoxWorldY1.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxWorldY1.TabIndex = 7;
            this.textBoxWorldY1.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxWorldY1.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxWorldX1.Location = new global::System.Drawing.Point(214, 79);
            this.textBoxWorldX1.Name = "textBoxWorldX1";
            this.textBoxWorldX1.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxWorldX1.TabIndex = 6;
            this.textBoxWorldX1.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxWorldX1.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxWorldY0.Location = new global::System.Drawing.Point(150, 79);
            this.textBoxWorldY0.Name = "textBoxWorldY0";
            this.textBoxWorldY0.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxWorldY0.TabIndex = 5;
            this.textBoxWorldY0.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxWorldY0.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxWorldX0.Location = new global::System.Drawing.Point(86, 79);
            this.textBoxWorldX0.Name = "textBoxWorldX0";
            this.textBoxWorldX0.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxWorldX0.TabIndex = 4;
            this.textBoxWorldX0.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxWorldX0.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxViewY1.Location = new global::System.Drawing.Point(278, 18);
            this.textBoxViewY1.Name = "textBoxViewY1";
            this.textBoxViewY1.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxViewY1.TabIndex = 3;
            this.textBoxViewY1.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxViewY1.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxViewX1.Location = new global::System.Drawing.Point(214, 18);
            this.textBoxViewX1.Name = "textBoxViewX1";
            this.textBoxViewX1.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxViewX1.TabIndex = 2;
            this.textBoxViewX1.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxViewX1.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxViewY0.Location = new global::System.Drawing.Point(150, 18);
            this.textBoxViewY0.Name = "textBoxViewY0";
            this.textBoxViewY0.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxViewY0.TabIndex = 1;
            this.textBoxViewY0.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxViewY0.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.textBoxViewX0.Location = new global::System.Drawing.Point(86, 18);
            this.textBoxViewX0.Name = "textBoxViewX0";
            this.textBoxViewX0.Size = new global::System.Drawing.Size(58, 19);
            this.textBoxViewX0.TabIndex = 0;
            this.textBoxViewX0.KeyDown += new global::System.Windows.Forms.KeyEventHandler(this.textBoxSceneTitle_KeyDown);
            this.textBoxViewX0.Leave += new global::System.EventHandler(this.textBoxSceneTitle_Leave);
            this.groupBox4.Controls.Add(this.label15);
            this.groupBox4.Controls.Add(this.label14);
            this.groupBox4.Controls.Add(this.btnBGColor);
            this.groupBox4.Controls.Add(this.comboBoxStyle);
            this.groupBox4.Location = new global::System.Drawing.Point(14, 908);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new global::System.Drawing.Size(351, 100);
            this.groupBox4.TabIndex = 5;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Rendering";
            this.label15.AutoSize = true;
            this.label15.Location = new global::System.Drawing.Point(22, 67);
            this.label15.Name = "label15";
            this.label15.Size = new global::System.Drawing.Size(96, 12);
            this.label15.TabIndex = 3;
            this.label15.Text = "Background Color";
            this.label14.AutoSize = true;
            this.label14.Location = new global::System.Drawing.Point(22, 21);
            this.label14.Name = "label14";
            this.label14.Size = new global::System.Drawing.Size(33, 12);
            this.label14.TabIndex = 2;
            this.label14.Text = "Style:";
            this.btnBGColor.Location = new global::System.Drawing.Point(143, 62);
            this.btnBGColor.Name = "btnBGColor";
            this.btnBGColor.Size = new global::System.Drawing.Size(75, 23);
            this.btnBGColor.TabIndex = 1;
            this.btnBGColor.UseVisualStyleBackColor = true;
            this.btnBGColor.MouseClick += new global::System.Windows.Forms.MouseEventHandler(this.btnBGColor_MouseClick);
            this.comboBoxStyle.FormattingEnabled = true;
            this.comboBoxStyle.Items.AddRange(new object[] { "Points", "Crosses", "Circles", "Blured", "Contour", "Textured" });
            this.comboBoxStyle.Location = new global::System.Drawing.Point(143, 18);
            this.comboBoxStyle.Name = "comboBoxStyle";
            this.comboBoxStyle.Size = new global::System.Drawing.Size(192, 20);
            this.comboBoxStyle.TabIndex = 0;
            this.comboBoxStyle.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxStyle_SelectedIndexChanged);
            this.groupBox5.Controls.Add(this.comboBoxBubbleTexture);
            this.groupBox5.Controls.Add(this.label21);
            this.groupBox5.Controls.Add(this.comboBoxSplashTexture);
            this.groupBox5.Controls.Add(this.label20);
            this.groupBox5.Controls.Add(this.comboBoxFireTexture);
            this.groupBox5.Controls.Add(this.label19);
            this.groupBox5.Controls.Add(this.comboBoxWaterTexture);
            this.groupBox5.Controls.Add(this.label18);
            this.groupBox5.Controls.Add(this.comboBoxBackTexture);
            this.groupBox5.Controls.Add(this.label17);
            this.groupBox5.Controls.Add(this.comboBoxForeTexture);
            this.groupBox5.Controls.Add(this.label16);
            this.groupBox5.Location = new global::System.Drawing.Point(14, 1014);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new global::System.Drawing.Size(350, 211);
            this.groupBox5.TabIndex = 6;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Images";
            this.comboBoxBubbleTexture.FormattingEnabled = true;
            this.comboBoxBubbleTexture.Location = new global::System.Drawing.Point(112, 161);
            this.comboBoxBubbleTexture.Name = "comboBoxBubbleTexture";
            this.comboBoxBubbleTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxBubbleTexture.TabIndex = 11;
            this.comboBoxBubbleTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxBubbleTexture_SelectedIndexChanged);
            this.label21.AutoSize = true;
            this.label21.Location = new global::System.Drawing.Point(21, 164);
            this.label21.Name = "label21";
            this.label21.Size = new global::System.Drawing.Size(42, 12);
            this.label21.TabIndex = 10;
            this.label21.Text = "Bubble:";
            this.comboBoxSplashTexture.FormattingEnabled = true;
            this.comboBoxSplashTexture.Location = new global::System.Drawing.Point(112, 135);
            this.comboBoxSplashTexture.Name = "comboBoxSplashTexture";
            this.comboBoxSplashTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxSplashTexture.TabIndex = 9;
            this.comboBoxSplashTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxSplashTexture_SelectedIndexChanged);
            this.label20.AutoSize = true;
            this.label20.Location = new global::System.Drawing.Point(21, 138);
            this.label20.Name = "label20";
            this.label20.Size = new global::System.Drawing.Size(41, 12);
            this.label20.TabIndex = 8;
            this.label20.Text = "Splash:";
            this.comboBoxFireTexture.FormattingEnabled = true;
            this.comboBoxFireTexture.Location = new global::System.Drawing.Point(112, 109);
            this.comboBoxFireTexture.Name = "comboBoxFireTexture";
            this.comboBoxFireTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxFireTexture.TabIndex = 7;
            this.comboBoxFireTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxFireTexture_SelectedIndexChanged);
            this.label19.AutoSize = true;
            this.label19.Location = new global::System.Drawing.Point(21, 112);
            this.label19.Name = "label19";
            this.label19.Size = new global::System.Drawing.Size(27, 12);
            this.label19.TabIndex = 6;
            this.label19.Text = "Fire:";
            this.comboBoxWaterTexture.FormattingEnabled = true;
            this.comboBoxWaterTexture.Location = new global::System.Drawing.Point(112, 83);
            this.comboBoxWaterTexture.Name = "comboBoxWaterTexture";
            this.comboBoxWaterTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxWaterTexture.TabIndex = 5;
            this.comboBoxWaterTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxWaterTexture_SelectedIndexChanged);
            this.label18.AutoSize = true;
            this.label18.Location = new global::System.Drawing.Point(21, 86);
            this.label18.Name = "label18";
            this.label18.Size = new global::System.Drawing.Size(61, 12);
            this.label18.TabIndex = 4;
            this.label18.Text = "Watermark:";
            this.comboBoxBackTexture.FormattingEnabled = true;
            this.comboBoxBackTexture.Location = new global::System.Drawing.Point(112, 57);
            this.comboBoxBackTexture.Name = "comboBoxBackTexture";
            this.comboBoxBackTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxBackTexture.TabIndex = 3;
            this.comboBoxBackTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxBackTexture_SelectedIndexChanged);
            this.label17.AutoSize = true;
            this.label17.Location = new global::System.Drawing.Point(21, 60);
            this.label17.Name = "label17";
            this.label17.Size = new global::System.Drawing.Size(67, 12);
            this.label17.TabIndex = 2;
            this.label17.Text = "Background:";
            this.comboBoxForeTexture.FormattingEnabled = true;
            this.comboBoxForeTexture.Location = new global::System.Drawing.Point(112, 31);
            this.comboBoxForeTexture.Name = "comboBoxForeTexture";
            this.comboBoxForeTexture.Size = new global::System.Drawing.Size(222, 20);
            this.comboBoxForeTexture.TabIndex = 1;
            this.comboBoxForeTexture.SelectedIndexChanged += new global::System.EventHandler(this.comboBoxForeTexture_SelectedIndexChanged);
            this.label16.AutoSize = true;
            this.label16.Location = new global::System.Drawing.Point(21, 34);
            this.label16.Name = "label16";
            this.label16.Size = new global::System.Drawing.Size(64, 12);
            this.label16.TabIndex = 0;
            this.label16.Text = "Foreground:";
            this.openFileDialog1.FileName = "openFileDialog1";
            this.btnSizeApply.Location = new global::System.Drawing.Point(180, 137);
            this.btnSizeApply.Name = "btnSizeApply";
            this.btnSizeApply.Size = new global::System.Drawing.Size(75, 23);
            this.btnSizeApply.TabIndex = 13;
            this.btnSizeApply.Text = "Apply";
            this.btnSizeApply.UseVisualStyleBackColor = true;
            this.btnSizeApply.Click += new global::System.EventHandler(this.btnSizeApply_Click);
            base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 12f);
            base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            base.ClientSize = new global::System.Drawing.Size(407, 573);
            base.Controls.Add(this.groupBox5);
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.groupSize);
            base.Controls.Add(this.groupScene);
            base.Name = "PropertyForm";
            this.Text = "Property";
            base.FormClosing += new global::System.Windows.Forms.FormClosingEventHandler(this.PropertyForm_FormClosing);
            this.groupScene.ResumeLayout(false);
            this.groupScene.PerformLayout();
            this.groupSize.ResumeLayout(false);
            this.groupSize.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((global::System.ComponentModel.ISupportInitialize)this.trackBarGravityAngle).EndInit();
            ((global::System.ComponentModel.ISupportInitialize)this.trackGravityAcc).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            base.ResumeLayout(false);
        }
        private global::System.ComponentModel.IContainer components;
        private global::System.Windows.Forms.GroupBox groupScene;
        private global::System.Windows.Forms.Label label2;
        private global::System.Windows.Forms.Label label1;
        private global::System.Windows.Forms.TextBox textBoxSceneDescription;
        private global::System.Windows.Forms.TextBox textBoxSceneTitle;
        private global::System.Windows.Forms.CheckBox checkBoxPublish;
        private global::System.Windows.Forms.GroupBox groupSize;
        private global::System.Windows.Forms.Label label5;
        private global::System.Windows.Forms.Label label4;
        private global::System.Windows.Forms.Label label3;
        private global::System.Windows.Forms.Button btnSizeDefault;
        private global::System.Windows.Forms.Label label6;
        private global::System.Windows.Forms.ComboBox comboBoxPixelsH;
        private global::System.Windows.Forms.ComboBox comboBoxPixelsW;
        private global::System.Windows.Forms.GroupBox groupBox1;
        private global::System.Windows.Forms.CheckBox checkBubbleEffect;
        private global::System.Windows.Forms.CheckBox checkSplashEffect;
        private global::System.Windows.Forms.CheckBox checkFireEffect;
        private global::System.Windows.Forms.CheckBox checkToolLimit;
        private global::System.Windows.Forms.CheckBox checkSound;
        private global::System.Windows.Forms.CheckBox checkBoundsWall;
        private global::System.Windows.Forms.GroupBox groupBox2;
        private global::System.Windows.Forms.TrackBar trackGravityAcc;
        private global::System.Windows.Forms.CheckBox checkGravity;
        private global::System.Windows.Forms.Label label8;
        private global::System.Windows.Forms.TextBox textBoxGravityAngle;
        private global::System.Windows.Forms.TrackBar trackBarGravityAngle;
        private global::System.Windows.Forms.TextBox textBoxGravityAcc;
        private global::System.Windows.Forms.Label label7;
        private global::System.Windows.Forms.GroupBox groupBox3;
        private global::System.Windows.Forms.GroupBox groupBox4;
        private global::System.Windows.Forms.GroupBox groupBox5;
        private global::System.Windows.Forms.TextBox textBoxWorldY1;
        private global::System.Windows.Forms.TextBox textBoxWorldX1;
        private global::System.Windows.Forms.TextBox textBoxWorldY0;
        private global::System.Windows.Forms.TextBox textBoxWorldX0;
        private global::System.Windows.Forms.TextBox textBoxViewY1;
        private global::System.Windows.Forms.TextBox textBoxViewX1;
        private global::System.Windows.Forms.TextBox textBoxViewY0;
        private global::System.Windows.Forms.TextBox textBoxViewX0;
        private global::System.Windows.Forms.TextBox textBoxBScrollY;
        private global::System.Windows.Forms.TextBox textBoxBScrollX;
        private global::System.Windows.Forms.Label label13;
        private global::System.Windows.Forms.TextBox textBoxFScrollY;
        private global::System.Windows.Forms.TextBox textBoxFScrollX;
        private global::System.Windows.Forms.Label label12;
        private global::System.Windows.Forms.TextBox textBoxAScrollY;
        private global::System.Windows.Forms.TextBox textBoxAScrollX;
        private global::System.Windows.Forms.Label label11;
        private global::System.Windows.Forms.CheckBox checkSleepOOV;
        private global::System.Windows.Forms.CheckBox checkWorldBounds;
        private global::System.Windows.Forms.Label label10;
        private global::System.Windows.Forms.Label label9;
        private global::System.Windows.Forms.Label label15;
        private global::System.Windows.Forms.Label label14;
        private global::System.Windows.Forms.Button btnBGColor;
        private global::System.Windows.Forms.ComboBox comboBoxStyle;
        private global::System.Windows.Forms.ComboBox comboBoxForeTexture;
        private global::System.Windows.Forms.Label label16;
        private global::System.Windows.Forms.ComboBox comboBoxBubbleTexture;
        private global::System.Windows.Forms.Label label21;
        private global::System.Windows.Forms.ComboBox comboBoxSplashTexture;
        private global::System.Windows.Forms.Label label20;
        private global::System.Windows.Forms.ComboBox comboBoxFireTexture;
        private global::System.Windows.Forms.Label label19;
        private global::System.Windows.Forms.ComboBox comboBoxWaterTexture;
        private global::System.Windows.Forms.Label label18;
        private global::System.Windows.Forms.ComboBox comboBoxBackTexture;
        private global::System.Windows.Forms.Label label17;
        private global::System.Windows.Forms.TextBox textBoxSceneWidth;
        private global::System.Windows.Forms.TextBox textBoxParticleSize;
        private global::System.Windows.Forms.TextBox textBoxSceneHeight;
        private global::System.Windows.Forms.ColorDialog colorDialogBGColor;
        private global::System.Windows.Forms.OpenFileDialog openFileDialog1;
        private global::System.Windows.Forms.TextBox textBoxTags;
        private global::System.Windows.Forms.Label label22;
        private global::System.Windows.Forms.Button btnSizeApply;
    }
}
