namespace WindowsViewer
{
    public partial class ToolForm : global::System.Windows.Forms.Form
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.radioPicker = new System.Windows.Forms.RadioButton();
            this.btnNowMaterial = new System.Windows.Forms.Button();
            this.btnMaterialColor = new System.Windows.Forms.Button();
            this.radioSpoit = new System.Windows.Forms.RadioButton();
            this.colorDialogMaterial = new System.Windows.Forms.ColorDialog();
            this.radioAxis = new System.Windows.Forms.RadioButton();
            this.radioSlice = new System.Windows.Forms.RadioButton();
            this.radioChgColor = new System.Windows.Forms.RadioButton();
            this.radioBucket = new System.Windows.Forms.RadioButton();
            this.radioShape = new System.Windows.Forms.RadioButton();
            this.radioBrush = new System.Windows.Forms.RadioButton();
            this.radioMove = new System.Windows.Forms.RadioButton();
            this.radioLink = new System.Windows.Forms.RadioButton();
            this.radioChgMaterial = new System.Windows.Forms.RadioButton();
            this.radioEraser = new System.Windows.Forms.RadioButton();
            this.radioMarker = new System.Windows.Forms.RadioButton();
            this.radioPen = new System.Windows.Forms.RadioButton();
            this.radioSelect = new System.Windows.Forms.RadioButton();
            this.radioArrow = new System.Windows.Forms.RadioButton();
            this.SuspendLayout();
            this.radioPicker.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioPicker.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioPicker.Location = new System.Drawing.Point(70, 13);
            this.radioPicker.Name = "radioPicker";
            this.radioPicker.Size = new System.Drawing.Size(52, 56);
            this.radioPicker.TabIndex = 28;
            this.radioPicker.UseVisualStyleBackColor = true;
            this.radioPicker.Visible = false;
            this.radioPicker.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.btnNowMaterial.Location = new System.Drawing.Point(12, 530);
            this.btnNowMaterial.Name = "btnNowMaterial";
            this.btnNowMaterial.Size = new System.Drawing.Size(110, 39);
            this.btnNowMaterial.TabIndex = 29;
            this.btnNowMaterial.Text = "button1";
            this.btnNowMaterial.UseVisualStyleBackColor = true;
            this.btnNowMaterial.Click += new System.EventHandler(this.btnNowMaterial_Click);
            this.btnMaterialColor.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.btnMaterialColor.Location = new System.Drawing.Point(12, 581);
            this.btnMaterialColor.Margin = new System.Windows.Forms.Padding(8, 9, 8, 9);
            this.btnMaterialColor.Name = "btnMaterialColor";
            this.btnMaterialColor.Size = new System.Drawing.Size(110, 39);
            this.btnMaterialColor.TabIndex = 30;
            this.btnMaterialColor.UseVisualStyleBackColor = false;
            this.btnMaterialColor.Click += new System.EventHandler(this.btnMaterialColor_Click);
            this.radioSpoit.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioSpoit.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioSpoit.Image = global::WindowsViewer.Properties.Resources.radioSpoit;
            this.radioSpoit.Location = new System.Drawing.Point(70, 453);
            this.radioSpoit.Name = "radioSpoit";
            this.radioSpoit.Size = new System.Drawing.Size(52, 56);
            this.radioSpoit.TabIndex = 32;
            this.radioSpoit.UseVisualStyleBackColor = true;
            this.radioSpoit.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioAxis.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioAxis.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioAxis.Image = global::WindowsViewer.Properties.Resources.radioAxis;
            this.radioAxis.Location = new System.Drawing.Point(12, 453);
            this.radioAxis.Name = "radioAxis";
            this.radioAxis.Size = new System.Drawing.Size(52, 56);
            this.radioAxis.TabIndex = 31;
            this.radioAxis.UseVisualStyleBackColor = true;
            this.radioAxis.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioSlice.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioSlice.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioSlice.Image = global::WindowsViewer.Properties.Resources.radioSlice;
            this.radioSlice.Location = new System.Drawing.Point(70, 390);
            this.radioSlice.Name = "radioSlice";
            this.radioSlice.Size = new System.Drawing.Size(52, 56);
            this.radioSlice.TabIndex = 27;
            this.radioSlice.UseVisualStyleBackColor = true;
            this.radioSlice.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioChgColor.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioChgColor.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioChgColor.Image = global::WindowsViewer.Properties.Resources.radioChgColor;
            this.radioChgColor.Location = new System.Drawing.Point(70, 327);
            this.radioChgColor.Name = "radioChgColor";
            this.radioChgColor.Size = new System.Drawing.Size(52, 56);
            this.radioChgColor.TabIndex = 26;
            this.radioChgColor.UseVisualStyleBackColor = true;
            this.radioChgColor.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioBucket.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioBucket.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioBucket.Image = global::WindowsViewer.Properties.Resources.radioBucket;
            this.radioBucket.Location = new System.Drawing.Point(70, 264);
            this.radioBucket.Name = "radioBucket";
            this.radioBucket.Size = new System.Drawing.Size(52, 56);
            this.radioBucket.TabIndex = 25;
            this.radioBucket.UseVisualStyleBackColor = true;
            this.radioBucket.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioShape.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioShape.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioShape.Image = global::WindowsViewer.Properties.Resources.radioShape;
            this.radioShape.Location = new System.Drawing.Point(70, 202);
            this.radioShape.Name = "radioShape";
            this.radioShape.Size = new System.Drawing.Size(52, 56);
            this.radioShape.TabIndex = 24;
            this.radioShape.UseVisualStyleBackColor = true;
            this.radioShape.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioBrush.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioBrush.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioBrush.Image = global::WindowsViewer.Properties.Resources.radioBrush;
            this.radioBrush.Location = new System.Drawing.Point(70, 139);
            this.radioBrush.Name = "radioBrush";
            this.radioBrush.Size = new System.Drawing.Size(52, 56);
            this.radioBrush.TabIndex = 23;
            this.radioBrush.UseVisualStyleBackColor = true;
            this.radioBrush.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioMove.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioMove.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioMove.Image = global::WindowsViewer.Properties.Resources.radioMove;
            this.radioMove.Location = new System.Drawing.Point(70, 76);
            this.radioMove.Name = "radioMove";
            this.radioMove.Size = new System.Drawing.Size(52, 56);
            this.radioMove.TabIndex = 22;
            this.radioMove.UseVisualStyleBackColor = true;
            this.radioMove.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioLink.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioLink.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioLink.Image = global::WindowsViewer.Properties.Resources.radioLink;
            this.radioLink.Location = new System.Drawing.Point(12, 390);
            this.radioLink.Name = "radioLink";
            this.radioLink.Size = new System.Drawing.Size(52, 56);
            this.radioLink.TabIndex = 21;
            this.radioLink.UseVisualStyleBackColor = true;
            this.radioLink.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioChgMaterial.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioChgMaterial.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioChgMaterial.Image = global::WindowsViewer.Properties.Resources.radioChgMaterial;
            this.radioChgMaterial.Location = new System.Drawing.Point(12, 327);
            this.radioChgMaterial.Name = "radioChgMaterial";
            this.radioChgMaterial.Size = new System.Drawing.Size(52, 56);
            this.radioChgMaterial.TabIndex = 20;
            this.radioChgMaterial.UseVisualStyleBackColor = true;
            this.radioChgMaterial.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioEraser.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioEraser.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioEraser.Image = global::WindowsViewer.Properties.Resources.radioEraser;
            this.radioEraser.Location = new System.Drawing.Point(12, 264);
            this.radioEraser.Name = "radioEraser";
            this.radioEraser.Size = new System.Drawing.Size(52, 56);
            this.radioEraser.TabIndex = 19;
            this.radioEraser.UseVisualStyleBackColor = true;
            this.radioEraser.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioMarker.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioMarker.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioMarker.Image = global::WindowsViewer.Properties.Resources.radioMarker;
            this.radioMarker.Location = new System.Drawing.Point(12, 202);
            this.radioMarker.Name = "radioMarker";
            this.radioMarker.Size = new System.Drawing.Size(52, 56);
            this.radioMarker.TabIndex = 18;
            this.radioMarker.UseVisualStyleBackColor = true;
            this.radioMarker.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioPen.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioPen.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioPen.Checked = true;
            this.radioPen.Image = global::WindowsViewer.Properties.Resources.radioPen;
            this.radioPen.Location = new System.Drawing.Point(12, 139);
            this.radioPen.Name = "radioPen";
            this.radioPen.Size = new System.Drawing.Size(52, 56);
            this.radioPen.TabIndex = 17;
            this.radioPen.TabStop = true;
            this.radioPen.UseVisualStyleBackColor = true;
            this.radioPen.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioSelect.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioSelect.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioSelect.Image = global::WindowsViewer.Properties.Resources.radioSelect;
            this.radioSelect.Location = new System.Drawing.Point(12, 76);
            this.radioSelect.Name = "radioSelect";
            this.radioSelect.Size = new System.Drawing.Size(52, 56);
            this.radioSelect.TabIndex = 16;
            this.radioSelect.UseVisualStyleBackColor = true;
            this.radioSelect.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.radioArrow.Appearance = System.Windows.Forms.Appearance.Button;
            this.radioArrow.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.radioArrow.Image = global::WindowsViewer.Properties.Resources.radioArrow;
            this.radioArrow.Location = new System.Drawing.Point(12, 13);
            this.radioArrow.Name = "radioArrow";
            this.radioArrow.Size = new System.Drawing.Size(52, 56);
            this.radioArrow.TabIndex = 14;
            this.radioArrow.UseVisualStyleBackColor = true;
            this.radioArrow.CheckedChanged += new System.EventHandler(this.Tool_CheckedChanged);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(136, 635);
            this.Controls.Add(this.radioSpoit);
            this.Controls.Add(this.radioAxis);
            this.Controls.Add(this.btnMaterialColor);
            this.Controls.Add(this.btnNowMaterial);
            this.Controls.Add(this.radioPicker);
            this.Controls.Add(this.radioSlice);
            this.Controls.Add(this.radioChgColor);
            this.Controls.Add(this.radioBucket);
            this.Controls.Add(this.radioShape);
            this.Controls.Add(this.radioBrush);
            this.Controls.Add(this.radioMove);
            this.Controls.Add(this.radioLink);
            this.Controls.Add(this.radioChgMaterial);
            this.Controls.Add(this.radioEraser);
            this.Controls.Add(this.radioMarker);
            this.Controls.Add(this.radioPen);
            this.Controls.Add(this.radioSelect);
            this.Controls.Add(this.radioArrow);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ToolForm";
            this.ShowIcon = false;
            this.ResumeLayout(false);
        }
        private global::System.ComponentModel.IContainer components;
        private global::System.Windows.Forms.RadioButton radioSlice;
        private global::System.Windows.Forms.RadioButton radioChgColor;
        private global::System.Windows.Forms.RadioButton radioBucket;
        private global::System.Windows.Forms.RadioButton radioShape;
        private global::System.Windows.Forms.RadioButton radioBrush;
        private global::System.Windows.Forms.RadioButton radioMove;
        private global::System.Windows.Forms.RadioButton radioLink;
        private global::System.Windows.Forms.RadioButton radioChgMaterial;
        private global::System.Windows.Forms.RadioButton radioEraser;
        private global::System.Windows.Forms.RadioButton radioMarker;
        private global::System.Windows.Forms.RadioButton radioPen;
        private global::System.Windows.Forms.RadioButton radioSelect;
        private global::System.Windows.Forms.RadioButton radioArrow;
        private global::System.Windows.Forms.RadioButton radioPicker;
        private global::System.Windows.Forms.Button btnNowMaterial;
        private global::System.Windows.Forms.Button btnMaterialColor;
        private global::System.Windows.Forms.RadioButton radioAxis;
        private global::System.Windows.Forms.RadioButton radioSpoit;
        private global::System.Windows.Forms.ColorDialog colorDialogMaterial;
    }
}
